DROP TABLE CUPOS;
DROP TABLE VENTAS;
DROP TABLE BOLETAS;
DROP TABLE CLASIFICACIONES;
DROP TABLE PREFERENCIAS;
DROP TABLE GENEROS;
DROP TABLE ESPECTADORES;
DROP TABLE FUNCIONES;
DROP TABLE ESPECIFICACIONES;
DROP TABLE SITIO_LOCALIDAD;
DROP TABLE LOCALIDADES;
DROP TABLE SITIOS;
DROP TABLE NECESIDADES;
DROP TABLE COMPANIA_ESPECTACULO;
DROP TABLE REQUERIMIENTOS_TECNICOS;
DROP TABLE ESPECTACULOS;
DROP TABLE COMPANIAS;
DROP TABLE CLIENTES;
DROP TABLE STAFF;

--------------------------------------------------------
--  DDL STAFF
--------------------------------------------------------
CREATE TABLE "ISIS2304B031710"."STAFF" 
   (	"ID" NUMBER CONSTRAINT "STAFF_ID_NN" NOT NULL ENABLE, 
	"DOC_ID" VARCHAR2(255 BYTE) CONSTRAINT "STAFF_DOC_ID_NN" NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(255 BYTE) CONSTRAINT "STAFF_NOMBRE_NN" NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(255 BYTE) CONSTRAINT "STAFF_PASSWORD_NN" NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"ROL" VARCHAR2(255 BYTE) CONSTRAINT "STAFF_ROL_NN" NOT NULL ENABLE, 
	 CONSTRAINT "STAFF_DOC_ID_UN" UNIQUE ("DOC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "STAFF_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "STAFF_ROL_IN" CHECK ("ROL"='administrador' OR "ROL"='operario') ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD";

--------------------------------------------------------
--  DDL CLIENTES
--------------------------------------------------------
CREATE TABLE "ISIS2304B031710"."CLIENTES" 
   (	"ID" NUMBER CONSTRAINT "CLIENTES_ID_NN" NOT NULL ENABLE, 
	"DOC_ID" VARCHAR2(255 BYTE) CONSTRAINT "CLIENTES_DOC_ID_NN" NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(255 BYTE) CONSTRAINT "CLIENTES_NOMBRE_NN" NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(255 BYTE) CONSTRAINT "CLIENTES_PASSWORD_NN" NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(255 BYTE) CONSTRAINT "CLIENTES_EMAIL_NN" NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	 CONSTRAINT "CLIENTES_DOC_ID_UN" UNIQUE ("DOC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "CLIENTES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD";
  
--------------------------------------------------------
--  DDL COMPANIAS
--------------------------------------------------------
CREATE TABLE "ISIS2304B031710"."COMPANIAS" 
   (	"ID" NUMBER CONSTRAINT "COMPANIAS_ID_NN" NOT NULL ENABLE, 
	"NIT" VARCHAR2(255 BYTE) CONSTRAINT "COMPANIAS_NIT_NN" NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(255 BYTE) CONSTRAINT "COMPANIAS_NOMBRE_NN" NOT NULL ENABLE, 
	"REPRESENTANTE" VARCHAR2(255 BYTE) CONSTRAINT "COMPANIA_REPRESENTANTE_NN" NOT NULL ENABLE, 
	"PAIS" VARCHAR2(255 BYTE) CONSTRAINT "COMPANIAS_PAIS_NN" NOT NULL ENABLE, 
	"WEB" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE) CONSTRAINT "COMPANIAS_PASSWORD_NN" NOT NULL ENABLE, 
	"LLEGADA" DATE CONSTRAINT "COMPANIAS_LLEGADA_NN" NOT NULL ENABLE, 
	"SALIDA" DATE CONSTRAINT "COMPANIAS_SALIDA_NN" NOT NULL ENABLE, 
	 CONSTRAINT "COMPANIAS" UNIQUE ("NIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "COMPANIAS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "COMPANIAS_SALIDA_CK" CHECK ("SALIDA">="LLEGADA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD";
  
--------------------------------------------------------
--  DDL ESPECTACULOS
--------------------------------------------------------
CREATE TABLE "ISIS2304B031710"."ESPECTACULOS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(225 BYTE) NOT NULL ENABLE, 
	"DURACION" NUMBER NOT NULL ENABLE, 
	"IDIOMA" VARCHAR2(225 BYTE), 
	"TRADUCTOR" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(225 BYTE), 
	"PUBLICOOBJ" VARCHAR2(225 BYTE), 
	 CONSTRAINT "ESPECTACULOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "PUBLICO_OBJ_CK" CHECK ("PUBLICOOBJ" IN ('infantil','jovenes','adultos','familia','todos')) ENABLE, 
	 CONSTRAINT "TRADUCTOR_CK" CHECK ("TRADUCTOR" IN ('s','n')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD";
  
--------------------------------------------------------
--  DDL REQUERIMIENTOS_TECNICOS
--------------------------------------------------------
CREATE TABLE "ISIS2304B031710"."REQUERIMIENTOS_TECNICOS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"REQUERIMIENTO" VARCHAR2(225 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "REQUERIMIENTOS_TECNICOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD";
  
--------------------------------------------------------
--  DDL COMPANIA_ESPECTACULO
--------------------------------------------------------
  CREATE TABLE "ISIS2304B031710"."COMPANIA_ESPECTACULO" 
   (	"ID_COMPANIA" NUMBER NOT NULL ENABLE, 
	"ID_ESPECTACULO" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "COMPANIA_ESPECTACULO_PK" PRIMARY KEY ("ID_COMPANIA", "ID_ESPECTACULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "COMPANIA_ESPECTACULO_FK1" FOREIGN KEY ("ID_ESPECTACULO")
	  REFERENCES "ISIS2304B031710"."ESPECTACULOS" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "COMPANIA_ESPECTACULO_FK2" FOREIGN KEY ("ID_COMPANIA")
	  REFERENCES "ISIS2304B031710"."COMPANIAS" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"   NO INMEMORY;

--------------------------------------------------------
--  DDL NECESIDADES
--------------------------------------------------------
CREATE TABLE "ISIS2304B031710"."NECESIDADES" 
   (	"ID_REQUERIMIENTO" NUMBER NOT NULL ENABLE, 
	"ID_ESPECTACULO" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "NECESIDADES_PK" PRIMARY KEY ("ID_REQUERIMIENTO", "ID_ESPECTACULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "NECESIDADES_FK1" FOREIGN KEY ("ID_REQUERIMIENTO")
	  REFERENCES "ISIS2304B031710"."REQUERIMIENTOS_TECNICOS" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "NECESIDADES_FK2" FOREIGN KEY ("ID_ESPECTACULO")
	  REFERENCES "ISIS2304B031710"."ESPECTACULOS" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD";
  
--------------------------------------------------------
--  DDL SITIOS
--------------------------------------------------------
  CREATE TABLE "ISIS2304B031710"."SITIOS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(225 BYTE) NOT NULL ENABLE, 
	"TIPO" VARCHAR2(225 BYTE) NOT NULL ENABLE, 
	"AFORO" NUMBER NOT NULL ENABLE, 
	"SILLETERIA" VARCHAR2(225 BYTE), 
	 CONSTRAINT "SITIOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD";
  
--------------------------------------------------------
--  DDL LOCALIDADES
--------------------------------------------------------
CREATE TABLE "ISIS2304B031710"."LOCALIDADES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(225 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "LOCALIDADES_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "ISIS2304B031710"."LOCALIDADES_PK1" ON "ISIS2304B031710"."LOCALIDADES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" )  ENABLE, 
	 CONSTRAINT "LOCALIDADES_NOMBRE_NN" CHECK (NOMBRE IS NOT NULL) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD";

--------------------------------------------------------
--  DDL SITIO_LOCALIDAD
--------------------------------------------------------
CREATE TABLE "ISIS2304B031710"."SITIO_LOCALIDAD" 
   (	"ID_SITIO" NUMBER NOT NULL ENABLE, 
	"ID_LOCALIDAD" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "SITIO_LOCALIDAD_PK" PRIMARY KEY ("ID_SITIO", "ID_LOCALIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "SITIO_LOCALIDAD_FK1" FOREIGN KEY ("ID_SITIO")
	  REFERENCES "ISIS2304B031710"."SITIOS" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "SITIO_LOCALIDAD_FK2" FOREIGN KEY ("ID_SITIO")
	  REFERENCES "ISIS2304B031710"."LOCALIDADES" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD";
  
--------------------------------------------------------
--  DDL ESPECIFICACIONES
--------------------------------------------------------
CREATE TABLE "ISIS2304B031710"."ESPECIFICACIONES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_SITIO" NUMBER NOT NULL ENABLE, 
	"ESPECIFICACION" VARCHAR2(225 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "ESPECIFICAIONES_PK" PRIMARY KEY ("ID", "ID_SITIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "ESPECIFICACIONES_FK1" FOREIGN KEY ("ID_SITIO")
	  REFERENCES "ISIS2304B031710"."SITIOS" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD";
  
--------------------------------------------------------
--  DDL FUNCIONES
--------------------------------------------------------
CREATE TABLE "ISIS2304B031710"."FUNCIONES" 
   (	"ID" NUMBER, 
	"ID_ESPECTACULO" NUMBER NOT NULL ENABLE, 
	"ID_SITIO" NUMBER NOT NULL ENABLE, 
	"DIA_REALIZACION" DATE NOT NULL ENABLE, 
	 CONSTRAINT "FUNCIONES_PK" PRIMARY KEY ("ID", "ID_ESPECTACULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "FUNCIONES_FK1" FOREIGN KEY ("ID_ESPECTACULO")
	  REFERENCES "ISIS2304B031710"."ESPECTACULOS" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FUNCIONES_FK2" FOREIGN KEY ("ID_SITIO")
	  REFERENCES "ISIS2304B031710"."SITIOS" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD";
  
--------------------------------------------------------
--  DDL ESPECTADORES
--------------------------------------------------------
CREATE TABLE "ISIS2304B031710"."ESPECTADORES" 
   (	"ID_ESPECTACULO" NUMBER NOT NULL ENABLE, 
	"ID_FUNCION" NUMBER NOT NULL ENABLE, 
	"ID_CLIENTE" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "ESPECTADORES_PK" PRIMARY KEY ("ID_ESPECTACULO", "ID_FUNCION")
  USING INDEX (CREATE UNIQUE INDEX "ISIS2304B031710"."ESPECTADORES_PK1" ON "ISIS2304B031710"."ESPECTADORES" ("ID_ESPECTACULO", "ID_FUNCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBSPROD" )  ENABLE, 
	 CONSTRAINT "ESPECTADORES_FK1" FOREIGN KEY ("ID_ESPECTACULO", "ID_FUNCION")
	  REFERENCES "ISIS2304B031710"."FUNCIONES" ("ID_ESPECTACULO", "ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "ESPECTADORES_FK2" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "ISIS2304B031710"."CLIENTES" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD";
  
--------------------------------------------------------
--  DDL GENEROS
--------------------------------------------------------
CREATE TABLE "ISIS2304B031710"."GENEROS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TIPO" VARCHAR2(225 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CATEGORIAS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "GENEROS_TIPO_UN" UNIQUE ("TIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD";

--------------------------------------------------------
--  DDL PREFERENCIAS
--------------------------------------------------------
CREATE TABLE "ISIS2304B031710"."PREFERENCIAS" 
   (	"ID_CLIENTE" NUMBER NOT NULL ENABLE, 
	"ID_GENERO" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PREFERENCIAS_PK" PRIMARY KEY ("ID_CLIENTE", "ID_GENERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "PREFERENCIAS_FK1" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "ISIS2304B031710"."CLIENTES" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "PREFERENCIAS_FK2" FOREIGN KEY ("ID_GENERO")
	  REFERENCES "ISIS2304B031710"."GENEROS" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD";

--------------------------------------------------------
--  DDL CLASIFICACIONES
--------------------------------------------------------
CREATE TABLE "ISIS2304B031710"."CLASIFICACIONES" 
   (	"ID_GENERO" NUMBER NOT NULL ENABLE, 
	"ID_ESPECTACULO" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "CLASIFICACIONES_PK" PRIMARY KEY ("ID_GENERO", "ID_ESPECTACULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "CLASIFICACIONES_FK1" FOREIGN KEY ("ID_GENERO")
	  REFERENCES "ISIS2304B031710"."GENEROS" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "CLASIFICACIONES_FK2" FOREIGN KEY ("ID_ESPECTACULO")
	  REFERENCES "ISIS2304B031710"."ESPECTACULOS" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD";

--------------------------------------------------------
--  DDL BOLETAS
--------------------------------------------------------
CREATE TABLE "ISIS2304B031710"."BOLETAS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_ESPECTACULO" NUMBER NOT NULL ENABLE, 
	"ID_FUNCION" NUMBER NOT NULL ENABLE, 
	"ID_SITIO" NUMBER NOT NULL ENABLE, 
	"VALOR" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "BOLETAS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE,  
	 CONSTRAINT "BOLETAS_FK1" FOREIGN KEY ("ID_ESPECTACULO", "ID_FUNCION")
	  REFERENCES "ISIS2304B031710"."FUNCIONES" ("ID_ESPECTACULO", "ID") ENABLE, 
	 CONSTRAINT "BOLETAS_FK2" FOREIGN KEY ("ID_SITIO")
	  REFERENCES "ISIS2304B031710"."SITIOS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD";
  
--------------------------------------------------------
--  DDL VENTAS
--------------------------------------------------------
CREATE TABLE "ISIS2304B031710"."VENTAS" 
   (	"ID_CLIENTE" NUMBER, 
	"ID_BOLETA" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "VENTAS_PK" PRIMARY KEY ("ID_CLIENTE", "ID_BOLETA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "VENTAS_FK1" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "ISIS2304B031710"."CLIENTES" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "VENTAS_FK2" FOREIGN KEY ("ID_BOLETA")
	  REFERENCES "ISIS2304B031710"."BOLETAS" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD";

--------------------------------------------------------
--  DDL VENTAS
--------------------------------------------------------
  CREATE TABLE "ISIS2304B031710"."CUPOS" 
   (	"ID_ESPECTACULO" NUMBER NOT NULL ENABLE, 
	"ID_FUNCION" NUMBER NOT NULL ENABLE, 
	"CUPO" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "CUPOS_PK" PRIMARY KEY ("ID_ESPECTACULO", "ID_FUNCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "CUPOS_CHK1" CHECK (CUPO >= 0) ENABLE, 
	 CONSTRAINT "CUPOS_FK1" FOREIGN KEY ("ID_FUNCION", "ID_ESPECTACULO")
	  REFERENCES "ISIS2304B031710"."FUNCIONES" ("ID", "ID_ESPECTACULO") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
  
COMMIT;