DROP TABLE STAFF;
DROP TABLE CLIENTES;
DROP TABLE COMPANIAS;
DROP TABLE FUNCIONES;
DROP TABLE ACONDICIONAMIENTO;
DROP TABLE CLASIFICACIONES;
DROP TABLE COMPANIAS;
DROP TABLE CONDICIONES_TECNICAS;
DROP TABLE ESPECIFICACIONES;
DROP TABLE LOCALIDADES;
DROP TABLE NECESIDADES;
DROP TABLE OFERTA_TEATRAL;
DROP TABLE REQUERIMIENTOS_TECNICOS;
DROP TABLE SITIOS;
DROP TABLE CATEGORIAS;
DROP TABLE FUNCIONES;
DROP TABLE SPECS;
DROP TABLE UBICACIONES;

CREATE TABLE STAFF
(
  ID_MIEMBRO NUMBER CONSTRAINT STAFF_ID_NN NOT NULL,
  DOC_ID_MIEMBRO VARCHAR2(255 BYTE) CONSTRAINT STAFF_DOC_ID_NN NOT NULL,
  NOMBRE_MIEMBRO VARCHAR2(255 BYTE) CONSTRAINT STAFF_NOMBRE_NN NOT NULL,
  PASSWORD_MIEMBRO VARCHAR2(255 BYTE) CONSTRAINT STAFF_PASSWORD_NN NOT NULL,
  EMAIL_MIEMBRO VARCHAR2(255 BYTE),
  ROL_MIEMBRO VARCHAR2(255 BYTE) CONSTRAINT STAFF_ROL_NN NOT NULL,
  CONSTRAINT STAFF_PK PRIMARY KEY (ID_MIEMBRO),
  CONSTRAINT STAFF_DOC_ID_UN UNIQUE (DOC_ID_MIEMBRO),
  CONSTRAINT STAFF_ROL_IN CHECK (ROL_MIEMBRO IN ('administrador', 'operario'))
);

INSERT INTO STAFF VALUES(1,'1','Julian','123','julian@email.com','administrador');

CREATE TABLE CLIENTES
(
  ID_CLIENTE NUMBER CONSTRAINT CLIENTES_ID_NN NOT NULL,
  DOC_ID_CLIENTE VARCHAR2(255 BYTE) CONSTRAINT CLIENTES_DOC_ID_NN NOT NULL,
  NOMBRE_CLIENTE VARCHAR2(255 BYTE) CONSTRAINT CLIENTES_NOMBRE_NN NOT NULL,
  PASSWORD_CLIENTE VARCHAR2(255 BYTE) CONSTRAINT CLIENTES_PASSWORD_NN NOT NULL,
  EMAIL_CLIENTE VARCHAR2(255 BYTE) CONSTRAINT CLIENTES_EMAIL_NN NOT NULL,
  ADDRESS_CLIENTE VARCHAR2(255 BYTE),
  CONSTRAINT CLIENTES_PK PRIMARY KEY (ID_CLIENTE),
  CONSTRAINT CLIENTES_DOC_ID_UN UNIQUE (DOC_ID_CLIENTE)
);

CREATE TABLE COMPANIAS
(
  ID_COMPANIA NUMBER CONSTRAINT COMPANIAS_ID_NN NOT NULL,
  NIT_COMPANIA VARCHAR2(255 BYTE) CONSTRAINT COMPANIAS_NIT_NN NOT NULL,
  NOMBRE_COMPANIA VARCHAR2(255 BYTE) CONSTRAINT COMPANIAS_NOMBRE_NN NOT NULL,
  REPRESENTANTE_COMPANIA VARCHAR2(255 BYTE) CONSTRAINT COMPANIA_REPRESENTANTE_NN NOT NULL,
  PAIS_COMPANIA VARCHAR2(255 BYTE) CONSTRAINT COMPANIAS_PAIS_NN NOT NULL,
  WEB_COMPANIA VARCHAR2(255 BYTE),
  PASSWORD_COMPANIA VARCHAR2(255 BYTE) CONSTRAINT COMPANIAS_PASSWORD_NN NOT NULL,
  LLEGADA_COMPANIA DATE CONSTRAINT COMPANIAS_LLEGADA_NN NOT NULL,
  SALIDA_COMPANIA DATE CONSTRAINT COMPANIAS_SALIDA_NN NOT NULL,
  CONSTRAINT COMPANIAS_PK PRIMARY KEY (ID_COMPANIA),
  CONSTRAINT COMPANIAS_NIT_UN UNIQUE (NIT_COMPANIA),
  CONSTRAINT COMPANIAS_SALIDA_CK CHECK (SALIDA_COMPANIA >= LLEGADA_COMPANIA)
);

CREATE TABLE FUNCIONES 
(
  ID NUMBER CONSTRAINT FUNCIONES_ID_NN NOT NULL, 
  ID_ESPECTACULO NUMBER CONSTRAINT FUNCIONES_ID_ESPECTACULO_NN NOT NULL,
  DIA_REALIZACION DATE CONSTRAINT FUNCIONES_DATE_NN NOT NULL, 
  CONSTRAINT FUNCIONES_PK PRIMARY KEY (ID, ID_ESPECTACULO)
  USING INDEX (CREATE UNIQUE INDEX TABLE1_PK ON FUNCIONES (ID ASC)) ENABLE 
);
--------------------------------------------------------
-- Archivo creado  - miércoles-marzo-22-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACONDICIONAMIENTO
--------------------------------------------------------

  CREATE TABLE "ISIS2304B031710"."ACONDICIONAMIENTO" 
   (	"SITIO" NUMBER, 
	"CONDICION" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table CATEGORIAS
--------------------------------------------------------

  CREATE TABLE "ISIS2304B031710"."CATEGORIAS" 
   (	"ID" NUMBER, 
	"TIPO" VARCHAR2(225 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table CLASIFICACIONES
--------------------------------------------------------

  CREATE TABLE "ISIS2304B031710"."CLASIFICACIONES" 
   (	"CATEGORIA" NUMBER, 
	"ESPECTACULO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "ISIS2304B031710"."CLIENTES" 
   (	"ID" NUMBER, 
	"NOMBRE_CLIENTE" VARCHAR2(225 BYTE), 
	"DOCUMENTO_CLIENTE" VARCHAR2(225 BYTE), 
	"EDAD" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table CONDICIONES_TECNICAS
--------------------------------------------------------

  CREATE TABLE "ISIS2304B031710"."CONDICIONES_TECNICAS" 
   (	"ID" NUMBER, 
	"CONDICION" VARCHAR2(225 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table ESPECIFICACIONES
--------------------------------------------------------

  CREATE TABLE "ISIS2304B031710"."ESPECIFICACIONES" 
   (	"SPEC" NUMBER, 
	"SITIO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table ESPECTACULOS
--------------------------------------------------------

  CREATE TABLE "ISIS2304B031710"."ESPECTACULOS" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(225 BYTE), 
	"DURACION" NUMBER, 
	"IDIOMA" VARCHAR2(225 BYTE), 
	"COSTO" NUMBER, 
	"TRADUCTOR" VARCHAR2(1 BYTE), 
	"DESCRIPCION" VARCHAR2(225 BYTE), 
	"PUBLICOOBJ" VARCHAR2(225 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table ESPECTADORES
--------------------------------------------------------

  CREATE TABLE "ISIS2304B031710"."ESPECTADORES" 
   (	"ESPECTACULO" NUMBER, 
	"CLIENTE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table LOCALIDADES
--------------------------------------------------------

  CREATE TABLE "ISIS2304B031710"."LOCALIDADES" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(225 BYTE), 
	"SITIO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table NECESIDADES
--------------------------------------------------------

  CREATE TABLE "ISIS2304B031710"."NECESIDADES" 
   (	"REQUERIMIENTO" NUMBER, 
	"ESPECTACULO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table OFERTA_TEATRAL
--------------------------------------------------------

  CREATE TABLE "ISIS2304B031710"."OFERTA_TEATRAL" 
   (	"COMPANIA" NUMBER, 
	"ESPECTACULO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table REQUERIMIENTOS_TECNICOS
--------------------------------------------------------

  CREATE TABLE "ISIS2304B031710"."REQUERIMIENTOS_TECNICOS" 
   (	"ID" NUMBER, 
	"REQUERIMIENTO" VARCHAR2(225 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table SITIOS
--------------------------------------------------------

  CREATE TABLE "ISIS2304B031710"."SITIOS" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(225 BYTE), 
	"TIPO" VARCHAR2(225 BYTE), 
	"AFORO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table SPECS
--------------------------------------------------------

  CREATE TABLE "ISIS2304B031710"."SPECS" 
   (	"ID" NUMBER, 
	"SPEC" VARCHAR2(225 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table UBICACIONES
--------------------------------------------------------

  CREATE TABLE "ISIS2304B031710"."UBICACIONES" 
   (	"FUNCION" NUMBER, 
	"SITIO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
REM INSERTING into ISIS2304B031710.ACONDICIONAMIENTO
SET DEFINE OFF;
REM INSERTING into ISIS2304B031710.CATEGORIAS
SET DEFINE OFF;
REM INSERTING into ISIS2304B031710.CLASIFICACIONES
SET DEFINE OFF;
REM INSERTING into ISIS2304B031710.CLIENTES
SET DEFINE OFF;
REM INSERTING into ISIS2304B031710.CONDICIONES_TECNICAS
SET DEFINE OFF;
REM INSERTING into ISIS2304B031710.ESPECIFICACIONES
SET DEFINE OFF;
REM INSERTING into ISIS2304B031710.ESPECTACULOS
SET DEFINE OFF;
REM INSERTING into ISIS2304B031710.ESPECTADORES
SET DEFINE OFF;
REM INSERTING into ISIS2304B031710.LOCALIDADES
SET DEFINE OFF;
REM INSERTING into ISIS2304B031710.NECESIDADES
SET DEFINE OFF;
REM INSERTING into ISIS2304B031710.OFERTA_TEATRAL
SET DEFINE OFF;
REM INSERTING into ISIS2304B031710.REQUERIMIENTOS_TECNICOS
SET DEFINE OFF;
REM INSERTING into ISIS2304B031710.SITIOS
SET DEFINE OFF;
REM INSERTING into ISIS2304B031710.SPECS
SET DEFINE OFF;
REM INSERTING into ISIS2304B031710.UBICACIONES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ACONDICIONAMIENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B031710"."ACONDICIONAMIENTO_PK" ON "ISIS2304B031710"."ACONDICIONAMIENTO" ("SITIO", "CONDICION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index CATEGORIAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B031710"."CATEGORIAS_PK" ON "ISIS2304B031710"."CATEGORIAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index CLASIFICACIONES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B031710"."CLASIFICACIONES_PK" ON "ISIS2304B031710"."CLASIFICACIONES" ("CATEGORIA", "ESPECTACULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index CLIENTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B031710"."CLIENTES_PK" ON "ISIS2304B031710"."CLIENTES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index CONDICIONES_TECNICAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B031710"."CONDICIONES_TECNICAS_PK" ON "ISIS2304B031710"."CONDICIONES_TECNICAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index ESPECIFICACIONES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B031710"."ESPECIFICACIONES_PK" ON "ISIS2304B031710"."ESPECIFICACIONES" ("SPEC", "SITIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index ESPECTACULOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B031710"."ESPECTACULOS_PK" ON "ISIS2304B031710"."ESPECTACULOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index ESPECTADORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B031710"."ESPECTADORES_PK" ON "ISIS2304B031710"."ESPECTADORES" ("ESPECTACULO", "CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index LOCALIDADES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B031710"."LOCALIDADES_PK" ON "ISIS2304B031710"."LOCALIDADES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index NECESIDADES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B031710"."NECESIDADES_PK" ON "ISIS2304B031710"."NECESIDADES" ("REQUERIMIENTO", "ESPECTACULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index OFERTATEATRAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B031710"."OFERTATEATRAL_PK" ON "ISIS2304B031710"."OFERTA_TEATRAL" ("COMPANIA", "ESPECTACULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index REQUERIMIENTOS_TECNICOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B031710"."REQUERIMIENTOS_TECNICOS_PK" ON "ISIS2304B031710"."REQUERIMIENTOS_TECNICOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index SITIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B031710"."SITIOS_PK" ON "ISIS2304B031710"."SITIOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index SPECS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B031710"."SPECS_PK" ON "ISIS2304B031710"."SPECS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index UBICACIONES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B031710"."UBICACIONES_PK" ON "ISIS2304B031710"."UBICACIONES" ("FUNCION", "SITIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  Constraints for Table ACONDICIONAMIENTO
--------------------------------------------------------

  ALTER TABLE "ISIS2304B031710"."ACONDICIONAMIENTO" ADD CONSTRAINT "ACONDICIONAMIENTO_PK" PRIMARY KEY ("SITIO", "CONDICION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B031710"."ACONDICIONAMIENTO" MODIFY ("SITIO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B031710"."ACONDICIONAMIENTO" MODIFY ("CONDICION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORIAS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B031710"."CATEGORIAS" ADD CONSTRAINT "CATEGORIAS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B031710"."CATEGORIAS" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B031710"."CATEGORIAS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLASIFICACIONES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B031710"."CLASIFICACIONES" ADD CONSTRAINT "CLASIFICACIONES_PK" PRIMARY KEY ("CATEGORIA", "ESPECTACULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B031710"."CLASIFICACIONES" MODIFY ("ESPECTACULO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B031710"."CLASIFICACIONES" MODIFY ("CATEGORIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B031710"."CLIENTES" ADD CONSTRAINT "CLIENTES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B031710"."CLIENTES" MODIFY ("DOCUMENTO_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B031710"."CLIENTES" MODIFY ("NOMBRE_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B031710"."CLIENTES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONDICIONES_TECNICAS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B031710"."CONDICIONES_TECNICAS" ADD CONSTRAINT "CONDICIONES_TECNICAS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B031710"."CONDICIONES_TECNICAS" MODIFY ("CONDICION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B031710"."CONDICIONES_TECNICAS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESPECIFICACIONES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B031710"."ESPECIFICACIONES" ADD CONSTRAINT "ESPECIFICACIONES_PK" PRIMARY KEY ("SPEC", "SITIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B031710"."ESPECIFICACIONES" MODIFY ("SITIO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B031710"."ESPECIFICACIONES" MODIFY ("SPEC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESPECTACULOS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B031710"."ESPECTACULOS" ADD CONSTRAINT "ESPECTACULOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B031710"."ESPECTACULOS" ADD CONSTRAINT "PUBLICO_OBJ_CK" CHECK ("PUBLICOOBJ" IN ('infantil','jovenes','adultos','familia','todos'));
  ALTER TABLE "ISIS2304B031710"."ESPECTACULOS" MODIFY ("TRADUCTOR" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B031710"."ESPECTACULOS" MODIFY ("COSTO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B031710"."ESPECTACULOS" MODIFY ("DURACION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B031710"."ESPECTACULOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B031710"."ESPECTACULOS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESPECTADORES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B031710"."ESPECTADORES" ADD CONSTRAINT "ESPECTADORES_PK" PRIMARY KEY ("ESPECTACULO", "CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B031710"."ESPECTADORES" MODIFY ("ESPECTACULO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B031710"."ESPECTADORES" MODIFY ("CLIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCALIDADES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B031710"."LOCALIDADES" ADD CONSTRAINT "LOCALIDADES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B031710"."LOCALIDADES" MODIFY ("SITIO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B031710"."LOCALIDADES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B031710"."LOCALIDADES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NECESIDADES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B031710"."NECESIDADES" ADD CONSTRAINT "NECESIDADES_PK" PRIMARY KEY ("REQUERIMIENTO", "ESPECTACULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B031710"."NECESIDADES" MODIFY ("ESPECTACULO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B031710"."NECESIDADES" MODIFY ("REQUERIMIENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OFERTA_TEATRAL
--------------------------------------------------------

  ALTER TABLE "ISIS2304B031710"."OFERTA_TEATRAL" ADD CONSTRAINT "OFERTATEATRAL_PK" PRIMARY KEY ("COMPANIA", "ESPECTACULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B031710"."OFERTA_TEATRAL" MODIFY ("ESPECTACULO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B031710"."OFERTA_TEATRAL" MODIFY ("COMPANIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REQUERIMIENTOS_TECNICOS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B031710"."REQUERIMIENTOS_TECNICOS" ADD CONSTRAINT "REQUERIMIENTOS_TECNICOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B031710"."REQUERIMIENTOS_TECNICOS" MODIFY ("REQUERIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B031710"."REQUERIMIENTOS_TECNICOS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SITIOS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B031710"."SITIOS" ADD CONSTRAINT "SITIOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B031710"."SITIOS" MODIFY ("AFORO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B031710"."SITIOS" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B031710"."SITIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B031710"."SITIOS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SPECS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B031710"."SPECS" ADD CONSTRAINT "SPECS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B031710"."SPECS" MODIFY ("SPEC" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B031710"."SPECS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UBICACIONES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B031710"."UBICACIONES" ADD CONSTRAINT "UBICACIONES_PK" PRIMARY KEY ("FUNCION", "SITIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B031710"."UBICACIONES" MODIFY ("SITIO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B031710"."UBICACIONES" MODIFY ("FUNCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ACONDICIONAMIENTO
--------------------------------------------------------

  ALTER TABLE "ISIS2304B031710"."ACONDICIONAMIENTO" ADD CONSTRAINT "ACONDICIONAMIENTO_FK1" FOREIGN KEY ("SITIO")
	  REFERENCES "ISIS2304B031710"."SITIOS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ISIS2304B031710"."ACONDICIONAMIENTO" ADD CONSTRAINT "ACONDICIONAMIENTO_FK2" FOREIGN KEY ("CONDICION")
	  REFERENCES "ISIS2304B031710"."CONDICIONES_TECNICAS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLASIFICACIONES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B031710"."CLASIFICACIONES" ADD CONSTRAINT "CLASIFICACIONES_FK1" FOREIGN KEY ("CATEGORIA")
	  REFERENCES "ISIS2304B031710"."CATEGORIAS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ISIS2304B031710"."CLASIFICACIONES" ADD CONSTRAINT "CLASIFICACIONES_FK2" FOREIGN KEY ("ESPECTACULO")
	  REFERENCES "ISIS2304B031710"."ESPECTACULOS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESPECIFICACIONES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B031710"."ESPECIFICACIONES" ADD CONSTRAINT "ESPECIFICACIONES_FK1" FOREIGN KEY ("SPEC")
	  REFERENCES "ISIS2304B031710"."SPECS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ISIS2304B031710"."ESPECIFICACIONES" ADD CONSTRAINT "ESPECIFICACIONES_FK2" FOREIGN KEY ("SITIO")
	  REFERENCES "ISIS2304B031710"."SITIOS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESPECTADORES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B031710"."ESPECTADORES" ADD CONSTRAINT "ESPECTADORES_FK1" FOREIGN KEY ("ESPECTACULO")
	  REFERENCES "ISIS2304B031710"."ESPECTACULOS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ISIS2304B031710"."ESPECTADORES" ADD CONSTRAINT "ESPECTADORES_FK2" FOREIGN KEY ("CLIENTE")
	  REFERENCES "ISIS2304B031710"."CLIENTES" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOCALIDADES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B031710"."LOCALIDADES" ADD CONSTRAINT "LOCALIDADES_FK1" FOREIGN KEY ("SITIO")
	  REFERENCES "ISIS2304B031710"."SITIOS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NECESIDADES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B031710"."NECESIDADES" ADD CONSTRAINT "NECESIDADES_FK1" FOREIGN KEY ("REQUERIMIENTO")
	  REFERENCES "ISIS2304B031710"."REQUERIMIENTOS_TECNICOS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ISIS2304B031710"."NECESIDADES" ADD CONSTRAINT "NECESIDADES_FK2" FOREIGN KEY ("ESPECTACULO")
	  REFERENCES "ISIS2304B031710"."ESPECTACULOS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OFERTA_TEATRAL
--------------------------------------------------------

  ALTER TABLE "ISIS2304B031710"."OFERTA_TEATRAL" ADD CONSTRAINT "OFERTATEATRAL_FK1" FOREIGN KEY ("ESPECTACULO")
	  REFERENCES "ISIS2304B031710"."ESPECTACULOS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ISIS2304B031710"."OFERTA_TEATRAL" ADD CONSTRAINT "OFERTATEATRAL_FK2" FOREIGN KEY ("COMPANIA")
	  REFERENCES "ISIS2304B031710"."COMPANIAS" ("ID_COMPANIA") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UBICACIONES
--------------------------------------------------------

  ALTER TABLE "ISIS2304B031710"."UBICACIONES" ADD CONSTRAINT "UBICACIONES_FK1" FOREIGN KEY ("FUNCION")
	  REFERENCES "ISIS2304B031710"."FUNCIONES" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ISIS2304B031710"."UBICACIONES" ADD CONSTRAINT "UBICACIONES_FK2" FOREIGN KEY ("SITIO")
	  REFERENCES "ISIS2304B031710"."SITIOS" ("ID") ON DELETE CASCADE ENABLE;
    
CREATE OR REPLACE TRIGGER COMPANIAS_LLEGADA_CK
  BEFORE INSERT OR UPDATE ON COMPANIAS
  FOR EACH ROW
BEGIN
  IF(:NEW.LLEGADA_COMPANIA >= SYSDATE)
  THEN
    RAISE_APPLICATION_ERROR(-20001, 'Date LLEGADA_COMPANIA must be earlier than or equal to the current date.');
  END IF;
END;

COMMIT;